//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yenisonproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kart_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kart_Table()
        {
            this.Alisveris_Table = new HashSet<Alisveris_Table>();
        }
    
        public int K_Id { get; set; }
        public string K_Bakiye { get; set; }
        public string K_Sahibi_Adı { get; set; }
        public string K_Sahibi_Soyadı { get; set; }
        public string K_Sahibi_Telefon { get; set; }
        public string K_Sahibi_Adres { get; set; }
        public string K_Sahibi_E_Posta { get; set; }
        public string K_Sifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alisveris_Table> Alisveris_Table { get; set; }
    }
}
