//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yenisonproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kasa_Table
    {
        public int Kas_P_Id { get; set; }
        public int Kas_Toplam_Hesap { get; set; }
        public System.DateTime Kas_Tarih { get; set; }
        public Nullable<int> Kas_Id { get; set; }
        public string Kas_Durum { get; set; }
    
        public virtual Kasa_Bilgi_Table Kasa_Bilgi_Table { get; set; }
        public virtual Personel_Table Personel_Table { get; set; }
    }
}
