//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yenisonproje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Magaza_DBEntities : DbContext
    {
        public Magaza_DBEntities()
            : base("name=Magaza_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alisveris_Table> Alisveris_Table { get; set; }
        public virtual DbSet<Kart_Table> Kart_Table { get; set; }
        public virtual DbSet<Kasa_Bilgi_Table> Kasa_Bilgi_Table { get; set; }
        public virtual DbSet<Market_Alim_Table> Market_Alim_Table { get; set; }
        public virtual DbSet<Personel_Table> Personel_Table { get; set; }
        public virtual DbSet<Urun_Table> Urun_Table { get; set; }
        public virtual DbSet<Kasa_Table> Kasa_Table { get; set; }
    }
}
