//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yenisonproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun_Table()
        {
            this.Alisveris_Table = new HashSet<Alisveris_Table>();
            this.Market_Alim_Table = new HashSet<Market_Alim_Table>();
        }
    
        public int U_Stok { get; set; }
        public string U_Marka { get; set; }
        public int U_Fiyat { get; set; }
        public string U_Acıklama { get; set; }
        public string U_Barkod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alisveris_Table> Alisveris_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Market_Alim_Table> Market_Alim_Table { get; set; }
    }
}
